(()=>{
'use strict';
const $=id=>document.getElementById(id);
const lab=$('graphics25dLab'),canvas=$('graphics25dCanvas'),open=$('open25dLabBtn'),close=$('close25dLabBtn');
if(!lab||!canvas||!open||!close)return;
const ctx=canvas.getContext('2d',{alpha:false}),ship=new Image();ship.src='assets/gallina_1.png';
const toggle=$('toggle25dViewBtn'),range=$('depth25dRange'),depthText=$('depth25dValue'),killsText=$('kills25dText');
let active=false,raf=0,last=0,dpr=1,w=1,h=1,mode25=true,depth=.65,kills=0;
let px=.5,py=.72,tx=.5,ty=.72,tilt=0,cool=0,shots=[],particles=[],stars=[],enemies=[];
function visibility(){open.style.display='block';}
function resetEnemies(){enemies=Array.from({length:5},(_,i)=>spawnEnemy(i));}
function spawnEnemy(i=0){return{x:.15+Math.random()*.7,y:.24+Math.random()*.30,hp:2,phase:Math.random()*6.28,speed:.25+Math.random()*.28,kind:i%3};}
function resize(){const r=lab.getBoundingClientRect();dpr=Math.min(2,devicePixelRatio||1);w=Math.max(1,r.width);h=Math.max(1,r.height);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);if(!stars.length)for(let i=0;i<120;i++)stars.push({x:Math.random(),y:Math.random(),z:.2+Math.random()*.8,s:.5+Math.random()*1.8});}
function project(x,y,z=0){if(!mode25)return{x:x*w,y:y*h,scale:1,depth:y};const horizon=h*.12,d=Math.max(.10,(y*h-horizon)/(h-horizon)),amt=depth;return{x:w*.5+(x-.5)*w*(1-amt*.32+amt*d*.32),y:(1-amt)*y*h+amt*(horizon+d*(h-horizon)),scale:1+amt*((.55+d*.72+z*.06)-1),depth:d};}
function burst(x,y,big=false){for(let i=0;i<(big?28:7);i++)particles.push({x,y,vx:(Math.random()-.5)*(big?.20:.05),vy:(Math.random()-.5)*(big?.20:.09),life:(big?.65:.35)+Math.random()*.35,size:big?2+Math.random()*5:2+Math.random()*2,hue:big?(Math.random()<.5?'#fbbf24':'#fb7185'):'#bae6fd'});}
function fire(){if(cool>0)return;cool=.16;shots.push({x:px,y:py-.05,t:0});burst(px,py-.055);}
function pointer(e,shoot=false){const r=canvas.getBoundingClientRect();tx=Math.max(.07,Math.min(.93,(e.clientX-r.left)/r.width));ty=Math.max(.24,Math.min(.9,(e.clientY-r.top)/r.height));if(shoot)fire();}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture?.(e.pointerId);pointer(e,true);});canvas.addEventListener('pointermove',e=>{if(e.buttons)pointer(e);});
function background(t){const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#020617');g.addColorStop(.48,'#111044');g.addColorStop(1,'#030712');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);const horizon=h*.12,glow=ctx.createRadialGradient(w*.5,horizon,0,w*.5,horizon,w*.7);glow.addColorStop(0,'rgba(99,102,241,.30)');glow.addColorStop(1,'rgba(2,6,23,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h*.75);for(const st of stars){const yy=(st.y+t*.000008*st.z)%1,p=project(st.x,yy*.92+.08);ctx.globalAlpha=.3+.7*st.z;ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(p.x,p.y,st.s*p.scale,0,6.29);ctx.fill();}ctx.globalAlpha=1;if(mode25&&depth>.05){ctx.strokeStyle='rgba(129,140,248,'+(.04+.09*depth)+')';for(let i=1;i<10;i++){const y=horizon+(h-horizon)*(i/10)**1.7;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}for(let i=-5;i<=5;i++){ctx.beginPath();ctx.moveTo(w*.5,horizon);ctx.lineTo(w*.5+i*w*.22,h);ctx.stroke();}}}
function drawEnemy(e){const p=project(e.x,e.y),r=22*p.scale;ctx.save();ctx.translate(p.x,p.y);ctx.shadowBlur=12;ctx.shadowColor=e.kind===0?'#f59e0b':e.kind===1?'#84cc16':'#ef4444';ctx.fillStyle=e.kind===0?'#fbbf24':e.kind===1?'#a3e635':'#fb7185';ctx.beginPath();for(let i=0;i<8;i++){const a=i*Math.PI/4,rr=i%2?r*.7:r;ctx.lineTo(Math.cos(a)*rr,Math.sin(a)*rr);}ctx.closePath();ctx.fill();ctx.fillStyle='#111827';ctx.beginPath();ctx.arc(-r*.28,-r*.08,r*.12,0,6.29);ctx.arc(r*.28,-r*.08,r*.12,0,6.29);ctx.fill();ctx.restore();}
function frame(now){if(!active)return;resize();const dt=Math.min(.035,(now-last)/1000||.016);last=now;cool=Math.max(0,cool-dt);const ox=px;px+=(tx-px)*Math.min(1,dt*5.5);py+=(ty-py)*Math.min(1,dt*5.5);tilt+=(Math.max(-.45,Math.min(.45,(px-ox)*35))-tilt)*Math.min(1,dt*7);background(now);
 for(const e of enemies){e.phase+=dt*e.speed;e.x+=Math.sin(e.phase)*dt*.045;if(e.x<.08)e.x=.08;if(e.x>.92)e.x=.92;}shots.forEach(s=>{s.t+=dt;s.y-=dt*.62;});
 for(const s of shots)for(const e of enemies){if(e.hp>0&&Math.abs(s.x-e.x)<.055&&Math.abs(s.y-e.y)<.045){e.hp--;s.t=99;burst(e.x,e.y,e.hp<=0);if(e.hp<=0){kills++;if(killsText)killsText.textContent='🎯 '+kills;setTimeout(()=>{Object.assign(e,spawnEnemy());},500);}}}
 shots=shots.filter(s=>s.y>.08&&s.t<2);for(const s of shots){const p=project(s.x,s.y,.08);ctx.save();ctx.shadowBlur=14;ctx.shadowColor='#67e8f9';ctx.strokeStyle='#a5f3fc';ctx.lineWidth=3*p.scale;ctx.beginPath();ctx.moveTo(p.x,p.y+18*p.scale);ctx.lineTo(p.x,p.y-14*p.scale);ctx.stroke();ctx.restore();}
 for(const e of enemies)if(e.hp>0)drawEnemy(e);particles.forEach(q=>{q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;});particles=particles.filter(q=>q.life>0);for(const q of particles){const p=project(q.x,q.y);ctx.globalAlpha=Math.min(1,q.life*2.5);ctx.fillStyle=q.hue;ctx.beginPath();ctx.arc(p.x,p.y,q.size*p.scale,0,6.29);ctx.fill();}ctx.globalAlpha=1;
 const p=project(px,py,.12),sw=94*p.scale,sh=94*p.scale;ctx.save();ctx.translate(p.x,p.y);if(mode25)ctx.transform(1,tilt*.18*depth,tilt*.35*depth,1,0,0);ctx.globalAlpha=.30;ctx.fillStyle='#020617';ctx.beginPath();ctx.ellipse(7,sh*.36,sw*.38,sh*.13,0,0,6.29);ctx.fill();ctx.globalAlpha=1;ctx.shadowBlur=22;ctx.shadowColor='rgba(56,189,248,.55)';if(ship.complete&&ship.naturalWidth)ctx.drawImage(ship,-sw/2,-sh/2,sw,sh);ctx.restore();raf=requestAnimationFrame(frame);}
function start(){active=true;kills=0;if(killsText)killsText.textContent='🎯 0';resetEnemies();lab.style.display='flex';$('startScreen')?.style.setProperty('display','none');last=performance.now();resize();raf=requestAnimationFrame(frame);}
function stop(){active=false;cancelAnimationFrame(raf);lab.style.display='none';$('startScreen')?.style.setProperty('display','flex');}
toggle?.addEventListener('click',()=>{mode25=!mode25;toggle.textContent='Vista: '+(mode25?'2.5D':'2D');});range?.addEventListener('input',()=>{depth=Number(range.value)/100;if(depthText)depthText.textContent=range.value+'%';});open.addEventListener('click',start);close.addEventListener('click',stop);window.addEventListener('resize',()=>active&&resize());visibility();
})();