"""Apply Play Games Services v2 to the Android project generated by Capacitor 8."""

from pathlib import Path
import re


root = Path("android/app")
gradle = root / "build.gradle"
manifest = root / "src/main/AndroidManifest.xml"
main_activity = root / "src/main/java/com/gallinacosmica/app/MainActivity.java"
application = root / "src/main/java/com/gallinacosmica/app/PlayGamesApplication.java"
plugin = root / "src/main/java/com/gallinacosmica/app/PlayGamesPlugin.java"
game_id = root / "src/main/res/values/play_games.xml"

for path in (gradle, manifest, main_activity):
    if not path.is_file():
        raise SystemExit(f"Missing Capacitor-generated file: {path}")

text = gradle.read_text()
if "play-services-games-v2" not in text:
    text, count = re.subn(
        r"(?m)^dependencies\s*\{",
        'dependencies {\n    implementation "com.google.android.gms:play-services-games-v2:22.1.0"',
        text,
        count=1,
    )
    if count != 1:
        raise SystemExit("Could not find app dependencies block")
    gradle.write_text(text)

text = manifest.read_text()
if "com.google.android.gms.games.APP_ID" not in text:
    if re.search(r"<application\b[^>]*\bandroid:name=", text, re.DOTALL):
        raise SystemExit("Application class already configured; inspect before changing it")
    text, count = re.subn(
        r"(<application\b[^>]*)(>)",
        r'\1\n        android:name="com.gallinacosmica.app.PlayGamesApplication"\2\n'
        '        <meta-data android:name="com.google.android.gms.games.APP_ID" '
        'android:value="@string/game_services_project_id" />',
        text,
        count=1,
        flags=re.DOTALL,
    )
    if count != 1:
        raise SystemExit("Could not find application element")
    manifest.write_text(text)

if not game_id.exists():
    game_id.write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<resources>\n'
        '    <string name="game_services_project_id" '
        'translatable="false">672762312251</string>\n'
        '</resources>\n'
    )

if not application.exists():
    application.write_text(
        'package com.gallinacosmica.app;\n\n'
        'import android.app.Application;\n'
        'import com.google.android.gms.games.PlayGamesSdk;\n\n'
        'public class PlayGamesApplication extends Application {\n'
        '    @Override\n'
        '    public void onCreate() {\n'
        '        super.onCreate();\n'
        '        PlayGamesSdk.initialize(this);\n'
        '    }\n'
        '}\n'
    )

if not plugin.exists():
    plugin.write_text(
        'package com.gallinacosmica.app;\n\n'
        'import com.getcapacitor.JSObject;\n'
        'import com.getcapacitor.Plugin;\n'
        'import com.getcapacitor.PluginCall;\n'
        'import com.getcapacitor.annotation.CapacitorPlugin;\n'
        'import com.getcapacitor.PluginMethod;\n'
        'import com.google.android.gms.games.PlayGames;\n'
        'import com.google.android.gms.common.api.ApiException;\n\n'
        '@CapacitorPlugin(name = "PlayGames")\n'
        'public class PlayGamesPlugin extends Plugin {\n'
        '    private String sha1ForSignature(android.content.pm.Signature signature) {\n'
        '        try {\n'
        '            byte[] digest = java.security.MessageDigest.getInstance("SHA-1")\n'
        '                .digest(signature.toByteArray());\n'
        '            StringBuilder fingerprint = new StringBuilder();\n'
        '            for (int index = 0; index < digest.length; index++) {\n'
        '                if (index > 0) fingerprint.append(":");\n'
        '                fingerprint.append(String.format(java.util.Locale.US, "%02X", digest[index] & 0xff));\n'
        '            }\n'
        '            return fingerprint.toString();\n'
        '        } catch (Exception error) {\n'
        '            return "No se pudo calcular SHA-1: " + error.getClass().getSimpleName()\n'
        '                + ": " + String.valueOf(error.getMessage());\n'
        '        }\n'
        '    }\n'
        '\n'
        '    private String describeSignatures(String label, android.content.pm.Signature[] signatures) {\n'
        '        if (signatures == null || signatures.length == 0) {\n'
        '            return label + ": ninguna firma disponible.";\n'
        '        }\n'
        '        StringBuilder detail = new StringBuilder(label)\n'
        '            .append(" (").append(signatures.length).append("):");\n'
        '        for (int index = 0; index < signatures.length; index++) {\n'
        '            detail.append("\\n- ").append(label).append(" #").append(index + 1)\n'
        '                .append(" SHA-1: ").append(sha1ForSignature(signatures[index]));\n'
        '        }\n'
        '        return detail.toString();\n'
        '    }\n'
        '\n'
        '    private String signingCertificateDetail() {\n'
        '        try {\n'
        '            String packageName = getActivity().getPackageName();\n'
        '            android.content.pm.PackageManager pm = getActivity().getPackageManager();\n'
        '            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.P) {\n'
        '                android.content.pm.PackageInfo info = pm.getPackageInfo(packageName,\n'
        '                    android.content.pm.PackageManager.GET_SIGNING_CERTIFICATES);\n'
        '                if (info.signingInfo == null) return "No se encontró información de firma.";\n'
        '                android.content.pm.SigningInfo signingInfo = info.signingInfo;\n'
        '                String detail = describeSignatures("Firmas vigentes del APK",\n'
        '                    signingInfo.getApkContentsSigners());\n'
        '                if (signingInfo.hasPastSigningCertificates()) {\n'
        '                    detail += "\\n" + describeSignatures("Historial de certificados",\n'
        '                        signingInfo.getSigningCertificateHistory());\n'
        '                } else {\n'
        '                    detail += "\\nHistorial de certificados: no disponible.";\n'
        '                }\n'
        '                return detail;\n'
        '            }\n'
        '            android.content.pm.PackageInfo info = pm.getPackageInfo(packageName,\n'
        '                android.content.pm.PackageManager.GET_SIGNATURES);\n'
        '            return describeSignatures("Firmas vigentes del APK", info.signatures)\n'
        '                + "\\nHistorial de certificados: Android anterior a 9.";\n'
        '        } catch (Exception error) {\n'
        '            return "No se pudieron leer las firmas: " + error.getClass().getSimpleName()\n'
        '                + ": " + String.valueOf(error.getMessage());\n'
        '        }\n'
        '    }\n'
        '\n'
        '    private String appConfigurationDetail() {\n'
        '        String packageName = getActivity().getPackageName();\n'
        '        try {\n'
        '            android.content.pm.PackageManager pm = getActivity().getPackageManager();\n'
        '            android.content.pm.PackageInfo packageInfo = pm.getPackageInfo(packageName, 0);\n'
        '            long versionCode = android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.P\n'
        '                ? packageInfo.getLongVersionCode() : packageInfo.versionCode;\n'
        '            int gameIdResource = getActivity().getResources().getIdentifier(\n'
        '                "game_services_project_id", "string", packageName);\n'
        '            String gameId = gameIdResource == 0 ? "No encontrado"\n'
        '                : getActivity().getString(gameIdResource);\n'
        '            String installer = pm.getInstallerPackageName(packageName);\n'
        '            return "Paquete Android: " + packageName\n'
        '                + "\\nVersión instalada: " + String.valueOf(packageInfo.versionName)\n'
        '                + " (código " + versionCode + ")"\n'
        '                + "\\nID Play Games incluido: " + gameId\n'
        '                + "\\nInstalador: " + (installer == null ? "desconocido" : installer);\n'
        '        } catch (Exception error) {\n'
        '            return "Paquete Android: " + packageName\n'
        '                + "\\nNo se pudo leer versión o ID: " + error.getClass().getSimpleName()\n'
        '                + ": " + String.valueOf(error.getMessage());\n'
        '        }\n'
        '    }\n\n'
        '    private String environmentDetail() {\n'
        '        int availability = com.google.android.gms.common.GoogleApiAvailability\n'
        '            .getInstance().isGooglePlayServicesAvailable(getActivity());\n'
        '        return appConfigurationDetail()\n'
        '            + "\\nFirmas detectadas por Android:\\n" + signingCertificateDetail()\n'
        '            + "\\nCódigo disponibilidad Google Play services: " + availability;\n'
        '    }\n\n'
        '    private String errorDetail(Exception error) {\n'
        '        if (error == null) return "Sin excepción entregada por Google Play Games.";\n'
        '        String detail = "Tipo: " + error.getClass().getName()\n'
        '            + "\\nMensaje: " + String.valueOf(error.getMessage())\n'
        '            + "\\nTexto completo: " + error.toString();\n'
        '        if (error instanceof ApiException) {\n'
        '            ApiException apiError = (ApiException) error;\n'
        '            detail += "\\nCódigo Play Games: " + apiError.getStatusCode()\n'
        '                + "\\nEstado API: " + String.valueOf(apiError.getStatus());\n'
        '        }\n'
        '        Throwable cause = error.getCause();\n'
        '        if (cause != null) {\n'
        '            detail += "\\nCausa: " + cause.getClass().getName()\n'
        '                + ": " + String.valueOf(cause.getMessage());\n'
        '        }\n'
        '        return detail + "\\n" + environmentDetail();\n'
        '    }\n\n'
        '    private void resolveAuthentication(PluginCall call) {\n'
        '        PlayGames.getGamesSignInClient(getActivity()).isAuthenticated()\n'
        '            .addOnCompleteListener(task -> {\n'
        '                JSObject result = new JSObject();\n'
        '                boolean authenticated = task.isSuccessful()\n'
        '                    && task.getResult().isAuthenticated();\n'
        '                String detail = task.isSuccessful()\n'
        '                    ? "isAuthenticated completó. Resultado autenticado: " + authenticated\n'
        '                    : errorDetail(task.getException());\n'
        '                result.put("authenticated", authenticated);\n'
        '                result.put("detail", detail);\n'
        '                result.put("diagnostic", detail + "\\n" + environmentDetail());\n'
        '                call.resolve(result);\n'
        '            });\n'
        '    }\n\n'
        '    @PluginMethod\n'
        '    public void getAuthStatus(PluginCall call) {\n'
        '        resolveAuthentication(call);\n'
        '    }\n\n'
        '    @PluginMethod\n'
        '    public void getPlayerStatus(PluginCall call) {\n'
        '        PlayGames.getPlayersClient(getActivity()).getCurrentPlayer()\n'
        '            .addOnCompleteListener(task -> {\n'
        '                JSObject result = new JSObject();\n'
        '                boolean playerAvailable = task.isSuccessful() && task.getResult() != null;\n'
        '                String detail = playerAvailable\n'
        '                    ? "Perfil de jugador disponible."\n'
        '                    : (task.isSuccessful() ? "getCurrentPlayer completó sin perfil." : errorDetail(task.getException()));\n'
        '                result.put("playerAvailable", playerAvailable);\n'
        '                result.put("detail", detail);\n'
        '                result.put("diagnostic", detail + "\\n" + environmentDetail());\n'
        '                call.resolve(result);\n'
        '            });\n'
        '    }\n\n'
        '    @PluginMethod\n'
        '    public void unlockAchievement(PluginCall call) {\n'
        '        String achievementId = call.getString("achievementId");\n'
        '        if (achievementId == null || achievementId.isEmpty()) {\n'
        '            call.reject("Falta el ID del logro.");\n'
        '            return;\n'
        '        }\n'
        '        PlayGames.getGamesSignInClient(getActivity()).isAuthenticated()\n'
        '            .addOnCompleteListener(task -> {\n'
        '                boolean authenticated = task.isSuccessful()\n'
        '                    && task.getResult().isAuthenticated();\n'
        '                if (!authenticated) {\n'
        '                    call.reject("Google Play Games no está autenticado.");\n'
        '                    return;\n'
        '                }\n'
        '                PlayGames.getAchievementsClient(getActivity()).unlock(achievementId);\n'
        '                JSObject result = new JSObject();\n'
        '                result.put("requested", true);\n'
        '                call.resolve(result);\n'
        '            });\n'
        '    }\n\n'
        '    @PluginMethod\n'
        '    public void signIn(PluginCall call) {\n'
        '        getActivity().runOnUiThread(() ->\n'
        '            PlayGames.getGamesSignInClient(getActivity()).signIn()\n'
        '                .addOnCompleteListener(task -> {\n'
        '                    if (!task.isSuccessful()) {\n'
        '                        call.reject(errorDetail(task.getException()));\n'
        '                        return;\n'
        '                    }\n'
        '                    JSObject result = new JSObject();\n'
        '                    boolean authenticated = task.getResult().isAuthenticated();\n'
        '                    String detail = "signIn completó. Resultado autenticado: " + authenticated\n'
        '                        + (authenticated ? "" : "\\nGoogle no entregó una excepción para este intento; la siguiente consulta de perfil mostrará el código disponible.")\n'
        '                        + "\\n" + environmentDetail();\n'
        '                    result.put("authenticated", authenticated);\n'
        '                    result.put("detail", detail);\n'
        '                    result.put("diagnostic", detail);\n'
        '                    call.resolve(result);\n'
        '                })\n'
        '        );\n'
        '    }\n'
        '}\n'
    )

text = main_activity.read_text()
if "PlayGamesPlugin.class" not in text:
    text, count = re.subn(
        r"public class MainActivity extends BridgeActivity\s*\{",
        'public class MainActivity extends BridgeActivity {\n'
        '    @Override\n'
        '    public void onCreate(android.os.Bundle savedInstanceState) {\n'
        '        registerPlugin(PlayGamesPlugin.class);\n'
        '        super.onCreate(savedInstanceState);\n'
        '        com.google.android.gms.games.GamesSignInClient gamesSignInClient =\n'
        '            com.google.android.gms.games.PlayGames.getGamesSignInClient(this);\n'
        '        gamesSignInClient.isAuthenticated()\n'
        '            .addOnCompleteListener(task -> {\n'
        '                boolean authenticated = task.isSuccessful()\n'
        '                    && task.getResult().isAuthenticated();\n'
        '                android.util.Log.i("PlayGames", "Authentication: "\n'
        '                    + (authenticated ? "success" : "automatic sign-in not available"));\n'
        '            });\n'
        '    }',
        text,
        count=1,
    )
    if count != 1:
        raise SystemExit("Could not find Capacitor MainActivity declaration")
    main_activity.write_text(text)

print("Play Games Services v2 configured for com.gallinacosmica.app")
